### ISSUE TITLE
源码中没有requirements.txt依赖文件吗

### ISSUE THREAD

**Issue by wytskshu** [youngWM/MyWeChatRecords#2]
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple执行报错

**Comment by youngWM** [comment]
遗漏了，你可以先在工程根目录位置使用命令  pip freeze > requirements.txt  自动生成，我晚上也会更新上传

**Comment by wytskshu** [comment]
我现在用V0.1.1的exe，运行一直卡在数据加载进度：63/64，微信版本3.9.11.19








&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youngWM/MyWeChatRecords"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 上午10:44
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [youngWM/MyWeChatRecords] 源码中没有requirements.txt依赖文件吗 (Issue #2)





 
遗漏了，你可以先在工程根目录位置使用命令  pip freeze &gt; requirements.txt  自动生成，我晚上也会更新上传
